### ISSUE TITLE
考虑android版本吗？

### ISSUE THREAD

**Issue by onlylikews** [TGIF-iMatrix/MXFlutter#1]
看代码只有IOS版本的实现，后续会考虑Android版本吗？

**Comment by Eden-Harris** [comment]
同问，使用JavaScriptCore的话和ReactNative一样, 不知道后续是否支持Android的动态更新，实在令人期待

**Comment by songxiaoliang** [comment]
同问

**Comment by mxflutter** [comment]
> 看代码只有IOS版本的实现，后续会考虑Android版本吗？

在计划中，完成之后会放出来。

**Comment by ping996** [comment]
请问android版本的release了么？

**Comment by oncealong** [comment]
![image](https://user-images.githubusercontent.com/5340073/70680197-60be1000-1cd2-11ea-91bb-d767bf0fbd71.png)
同问，我看README上写了支持Android，目前开源的这个支持Android么？

**Comment by mxflutter** [comment]
0.0.3版本已支持，0.0.1版本在开发中
