### ISSUE TITLE
额，文档链接错了……

### ISSUE THREAD

**Issue by lwlizhe** [TGIF-iMatrix/MXFlutter#10]
现在的链接后面少了 .md……

顺便想提一个小疑问点……

这个库是针对ios设备做的么，看像 JavasSriptCore 这个技术点是面向ios的，文档说明也没提到跨平台这块的，所以，做为一个Android程序员，自然想知道在Android这块的支持怎么样呢?

**Comment by mxflutter** [comment]
> 后面少了 .md……

感谢指出，因为人力原因，android在计划中，可能没有那么快
