### ISSUE TITLE
如何实现动态下发

### ISSUE THREAD

**Issue by LinXiaoTao** [TGIF-iMatrix/MXFlutter#14]
你好，README 中说是一个动态框架，请问这个动态是如何实现？比如怎么生成增量包等等

**Comment by HansRove** [comment]
这个我想想知道.     1.4K star的项目没有大佬回复么??

**Comment by HansRove** [comment]
初略了解了一下:  大概就是网络下载JS替换掉包里JS对应文件, 然后重启JSAPP .   
 NSString *jsRootDir = [JSFLUTTER_SRC_BASE_DIR stringByAppendingPathComponent:JSFLUTTER_SRC_DIR];

这是js的根目录文件, 你可以从网络下载对应名字的js文件替换掉对应的文件.     本地动态, 因为虚拟机本身的路径是读取项目中的蓝色JS文件夹, 所以修改(蓝色文件夹里的JS)完后点击第一启动页的reload在看你修改的地方, 应该就动态了

**Comment by mxflutter** [comment]
> 你好，README 中说是一个动态框架，请问这个动态是如何实现？比如怎么生成增量包等等

如HansRove同学回答，是在此处更换JS文件，MXFlutter 目前放出的是技术预览版本，如果要使用，必须非常了解Flutter，JS等运行原理， 如没有读懂源码，建议先不要使用。MXFlutter将会有一个大版本更新，完善了这此问题，敬请期待。
