### ISSUE TITLE
请问一下, Demo知乎JS中的数据能不能使用网络请求回来的数据源

### ISSUE THREAD

**Issue by HansRove** [TGIF-iMatrix/MXFlutter#17]
如题,  如果可以如何再setState页面

**Comment by OOMROO** [comment]
网络请求是放在Flutter层还是JS层，如果在Flutter 层如何给JS（页面）配置数据?

**Comment by HansRove** [comment]
JS能否作为flutter启动后的第一个page ?

**Comment by mxflutter** [comment]
> 如题, 如果可以如何再setState页面

MXFlutter 目前放出的是技术预览版本，如果要使用，必须非常了解Flutter，JS等运行原理， 要实现从网络获取数据，目前可以使用JSCode和原生通讯能力，MXFlutter将会有一个大版本更新，完善了此问题，敬请期待。

**Comment by mxflutter** [comment]
> 如题, 如果可以如何再setState页面
> JS能否作为flutter启动后的第一个page ?

0.1.0版本已支持网络库dio

JS能否作为flutter启动后的第一个page ,可以搜索以下代码，打开注释，不过Flutter引擎和JS引擎有一定启动时间，有一段时间白屏，可能需要在Native侧做个启动页面，缓解白屏时间。
  // 2.MXJSPage： 直接打开MXFlutter写的页面，TODO：JS引擎启动需要时间，这里会展示菊花，优化中。。。
    //NSString *route  = @"MXJSPage";
