### ISSUE TITLE
ios 13.1 运行白屏

### ISSUE THREAD

**Issue by Tonigt** [TGIF-iMatrix/MXFlutter#18]
2019-10-28 15:29:09.747591+0800 Runner[6356:2276084] Metal API Validation Enabled
2019-10-28 15:29:10.095575+0800 Runner[6356:2276355] flutter: Observatory listening on http://127.0.0.1:57170/X5EtNoo0FL4=/
2019-10-28 15:29:10.371420+0800 Runner[6356:2276357] [VERBOSE-2:ui_dart_state.cc(144)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
#1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
#2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
#3      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:368:5)
#4      MXJSFlutter.setupChannel (package:js_flutter/js_flutter/mx_js_framework.dart:45:27)
#5      MXJSFlutter.setup (package:js_flutter/js_flutter/mx_js_framework.dart:40:5)
#6      main (package:js_flutter/main.dart:11:29)
#7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1500:12)
#12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by HansRove** [comment]
> 2019-10-28 15:29:09.747591+0800 Runner[6356:2276084] Metal API Validation Enabled
> 2019-10-28 15:29:10.095575+0800 Runner[6356:2276355] flutter: Observatory listening on http://127.0.0.1:57170/X5EtNoo0FL4=/
> 2019-10-28 15:29:10.371420+0800 Runner[6356:2276357] [VERBOSE-2:ui_dart_state.cc(144)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
> If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
> If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
> #0 defaultBinaryMessenger. (package:flutter/src/services/binary_messenger.dart:73:7)
> #1 defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
> #2 MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
> #3 MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:368:5)
> #4 MXJSFlutter.setupChannel (package:js_flutter/js_flutter/mx_js_framework.dart:45:27)
> #5 MXJSFlutter.setup (package:js_flutter/js_flutter/mx_js_framework.dart:40:5)
> #6 main (package:js_flutter/main.dart:11:29)
> #7 _runMainZoned.. (dart:ui/hooks.dart:239:25)
> #8 _rootRun (dart:async/zone.dart:1124:13)
> #9 _CustomZone.run (dart:async/zone.dart:1021:19)
> #10 _runZoned (dart:async/zone.dart:1516:10)
> #11 runZoned (dart:async/zone.dart:1500:12)
> #12 _runMainZoned. (dart:ui/hooks.dart:231:5)
> #13 _startIsolate. (dart:isolate-patch/isolate_patch.dart:305:19)
> #14 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

你的flutter版本是多少? 我的是1.9.7   需要在main.dart文件-main()函数里加一行: WidgetsFlutterBinding.ensureInitialized();    在MXJSFlutter这个调用前.   你的错误提示也有说明, 你可以试一下!!

**Comment by Tonigt** [comment]
好的  解决了  谢谢了，之前在 runApp()前面加的



------------------ 原始邮件 ------------------
发件人: "黄荣威"<notifications@github.com>; 
发送时间: 2019年10月28日(星期一) 下午3:36
收件人: "TGIF-iMatrix/MXFlutter"<MXFlutter@noreply.github.com>; 
抄送: "lonely"<1984701289@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TGIF-iMatrix/MXFlutter] ios 13.1 运行白屏 (#18)



 
2019-10-28 15:29:09.747591+0800 Runner[6356:2276084] Metal API Validation Enabled
 2019-10-28 15:29:10.095575+0800 Runner[6356:2276355] flutter: Observatory listening on http://127.0.0.1:57170/X5EtNoo0FL4=/
 2019-10-28 15:29:10.371420+0800 Runner[6356:2276357] [VERBOSE-2:ui_dart_state.cc(144)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
 If you're running an application and need to access the binary messenger before runApp() has been called (for example, during plugin initialization), then you need to explicitly call the WidgetsFlutterBinding.ensureInitialized() first.
 If you're running a test, you can call the TestWidgetsFlutterBinding.ensureInitialized() as the first line in your test's main() method to initialize the binding.
 #0 defaultBinaryMessenger. (package:flutter/src/services/binary_messenger.dart:73:7)
 #1 defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
 #2 MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
 #3 MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:368:5)
 #4 MXJSFlutter.setupChannel (package:js_flutter/js_flutter/mx_js_framework.dart:45:27)
 #5 MXJSFlutter.setup (package:js_flutter/js_flutter/mx_js_framework.dart:40:5)
 #6 main (package:js_flutter/main.dart:11:29)
 #7 _runMainZoned.. (dart:ui/hooks.dart:239:25)
 #8 _rootRun (dart:async/zone.dart:1124:13)
 #9 _CustomZone.run (dart:async/zone.dart:1021:19)
 #10 _runZoned (dart:async/zone.dart:1516:10)
 #11 runZoned (dart:async/zone.dart:1500:12)
 #12 _runMainZoned. (dart:ui/hooks.dart:231:5)
 #13 _startIsolate. (dart:isolate-patch/isolate_patch.dart:305:19)
 #14 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
  
你的flutter版本是多少? 我的是1.9.7   需要在main.dart文件-main()函数里加一行: WidgetsFlutterBinding.ensureInitialized();    在MXJSFlutter这个调用前.   你的错误提示也有说明, 你可以试一下!!

**Comment by Tonigt** [comment]
还有个问题啊，mxflutter 怎么调用原生的dart呢 ？



------------------ 原始邮件 ------------------
发件人: "黄荣威"<notifications@github.com>; 
发送时间: 2019年10月28日(星期一) 下午3:36
收件人: "TGIF-iMatrix/MXFlutter"<MXFlutter@noreply.github.com>; 
抄送: "lonely"<1984701289@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TGIF-iMatrix/MXFlutter] ios 13.1 运行白屏 (#18)



 
2019-10-28 15:29:09.747591+0800 Runner[6356:2276084] Metal API Validation Enabled
 2019-10-28 15:29:10.095575+0800 Runner[6356:2276355] flutter: Observatory listening on http://127.0.0.1:57170/X5EtNoo0FL4=/
 2019-10-28 15:29:10.371420+0800 Runner[6356:2276357] [VERBOSE-2:ui_dart_state.cc(144)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
 If you're running an application and need to access the binary messenger before runApp() has been called (for example, during plugin initialization), then you need to explicitly call the WidgetsFlutterBinding.ensureInitialized() first.
 If you're running a test, you can call the TestWidgetsFlutterBinding.ensureInitialized() as the first line in your test's main() method to initialize the binding.
 #0 defaultBinaryMessenger. (package:flutter/src/services/binary_messenger.dart:73:7)
 #1 defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
 #2 MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
 #3 MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:368:5)
 #4 MXJSFlutter.setupChannel (package:js_flutter/js_flutter/mx_js_framework.dart:45:27)
 #5 MXJSFlutter.setup (package:js_flutter/js_flutter/mx_js_framework.dart:40:5)
 #6 main (package:js_flutter/main.dart:11:29)
 #7 _runMainZoned.. (dart:ui/hooks.dart:239:25)
 #8 _rootRun (dart:async/zone.dart:1124:13)
 #9 _CustomZone.run (dart:async/zone.dart:1021:19)
 #10 _runZoned (dart:async/zone.dart:1516:10)
 #11 runZoned (dart:async/zone.dart:1500:12)
 #12 _runMainZoned. (dart:ui/hooks.dart:231:5)
 #13 _startIsolate. (dart:isolate-patch/isolate_patch.dart:305:19)
 #14 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
  
你的flutter版本是多少? 我的是1.9.7   需要在main.dart文件-main()函数里加一行: WidgetsFlutterBinding.ensureInitialized();    在MXJSFlutter这个调用前.   你的错误提示也有说明, 你可以试一下!!
