### ISSUE TITLE
既然用js实现了可以带上预编译器么？

### ISSUE THREAD

**Issue by luanwulin** [TGIF-iMatrix/MXFlutter#2]
比如flutter最受诟病的return，用jsx写法实现，最后用babel转为目标js代码

**Comment by mxflutter** [comment]
> 比如flutter最受诟病的return，用jsx写法实现，最后用babel转为目标js代码

这个想法很赞，我们目前还没有这个计划，先完美支持Flutter语法，我们会讨论一下。感谢建议。

**Comment by luanwulin** [comment]
@TGIF-iMatrix 好的呢~，但愿能看到你们一直维护下去，早日用上正式版

**Comment by anthhub** [comment]
最好能支持ts

**Comment by xuweishun** [comment]
Android运行就报错了  
): MXJSFlutter:[Flutter]-callJSWidget:MethodCall(flutterCallOnInitState, {widgetID: null, buildSeq: null})
I/flutter (21575): MXJSFlutter:[Flutter]-MXJSWidget:build: null 
E/flutter (21575): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method callJS on channel js_flutter.js_flutter_app_channel)
E/flutter (21575): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter (21575): <asynchronous suspension>
E/flutter (21575): #1      MXJSFlutterApp.callJS (package:js_flutter/js_flutter/mx_js_framework.dart:228:26)
E/flutter (21575): #2      MXJSFlutterApp.callJSNavigatorPushWithPageName (package:js_flutter/js_flutter/mx_js_framework.dart:203:5)
E/flutter (21575): <asynchronous suspension>
E/flutter (21575): #3      MXJSFlutterApp.navigatorPushWithPageName (package:js_flutter/js_flutter/mx_js_framework.dart:160:5)
E/flutter (21575): #4      MXJSFlutter.navigatorPushWithPageName (package:js_flutter/js_flutter/mx_js_framework.dart:92:39)
E/flutter (21575): #5      _DemoList.build.<anonymous closure>.<anonymous closure> (package:js_flutter/main.dart:116:24)
E/flutter (21575): #6      MaterialPageRoute.buildPage (package:flutter/src/material/page.dart:87:27)
E/flutter (21575): #7      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:651:43)
E/flutter (21575): #8      Builder.build (package:flutter/src/widgets/basic.dart:6233:41)
E/flutter (21575): #9      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
E/flutter (21575): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
E/flutter (21575): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (21575): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (21575): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (21575): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (21575): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (21575): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (21575): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (21575): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (21575): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (21575): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (21575): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (21575): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (21575): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (21575): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (21575): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (21575): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (21575): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (21575): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (21575): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (21575): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (21575): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter (21575): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (21575): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (21575): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (21575): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (21575): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (21575): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (21575): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (21575): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (21575): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (21575): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (21575): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (21575): #43     ComponentElement._firstBuild (package:flutter/src

**Comment by mxflutter** [comment]
预编译计划暂时搁置
