### ISSUE TITLE
关于 Hippy

### ISSUE THREAD

**Issue by anthhub** [TGIF-iMatrix/MXFlutter#21]
想问一下怎么评价qq浏览器团队开源的 Hippy 呢？ 个人感觉可能Hippy发展可能更好一些。。。

**Comment by mxflutter** [comment]
> 想问一下怎么评价qq浏览器团队开源的 Hippy 呢？ 个人感觉可能Hippy发展可能更好一些。。。

Hippy 是类似ReactNative的框架，但相比RN做了很多性能优化，可以尝试一下，MXFlutter是基于Flutter技术栈，两者方向不同，MXFlutter将会有一个大版本更新，敬请期待。
