### ISSUE TITLE
复杂控件刷新问题

### ISSUE THREAD

**Issue by wayu002** [TGIF-iMatrix/MXFlutter#23]
问题场景：
1. 自定义控件A，A内部包含自定义控件B。
2. B由于某些触发因素（如：动画、点击等）通过js 通知 flutter端rebuild。
3. A由于某些因素（如：ListView滚动）导致从Flutter端发起build流程。

问题现象：
此时B控件的状态没有保存住，被重置了，比如B控件显示动画之前的UI状态。

原因分析：
从源码中，感觉是因为当A build时，保存了整个控件的widgetData，当B被build时，只有B控件自身进行了更新，A中保存的widgetDdata没有更新，所以当A由于flutter端触发的build操作，使用的还是旧的widgetData，显示出来的B控件就变成旧的UI样式了。

希望状态管理这块内容在新版本能有更好的更直观的使用方式。

**Comment by mxflutter** [comment]
感谢反馈，我们已经注意到了这个问题，将使用类似KeepAlives的设计来解决这个问题。

**Comment by mxflutter** [comment]
v0.8.0已支持嵌套widget的状态保持
