### ISSUE TITLE
Demo Android 所有动画不能执行，IOS可以执行

### ISSUE THREAD

**Issue by coderLM** [TGIF-iMatrix/MXFlutter#26]
文件：/js_flutter_src/app_test/animation.js
Flutter SDK Version：1.12.13+hotfix.5
附件为IOS、Android平台打开此页面的log。
发现Android多执行了一次Center的build，不知否是此原因造成的。
[ios_anim.log](https://github.com/TGIF-iMatrix/MXFlutter/files/4379557/ios_anim.log)
[android_anim.log](https://github.com/TGIF-iMatrix/MXFlutter/files/4379560/android_anim.log)

PS: Demo-->UI Demo-->Examples-->动画组件 中好多项页面Android上打不开

**Comment by coderLM** [comment]
原因找到了，Android端 运行时invoke方法产生的 json串的params部分比IOS多了一层 invokeParams
(invoke, {invokeParams: {"mirrorID":"1","className":"AnimationController","funcName":"forward","args":{}}})

**Comment by mxflutter** [comment]
> 原因找到了，Android端 运行时invoke方法产生的 json串的params部分比IOS多了一层 invokeParams
> (invoke, {invokeParams: {"mirrorID":"1","className":"AnimationController","funcName":"forward","args":{}}})

感谢 coderLM
