### ISSUE TITLE
能否透露大版本更新的时间，感谢！

### ISSUE THREAD

**Issue by coderLM** [TGIF-iMatrix/MXFlutter#27]
最近项目组准备在线上的项目中应用MXFlutter，大佬能否透露一下大版本更新的时间。
感谢！

**Comment by mxflutter** [comment]
> 最近项目组准备在线上的项目中应用MXFlutter，大佬能否透露一下大版本更新的时间。
> 感谢！

我们加快一些，计划 3月29日 主库更新一个版本

**Comment by coderLM** [comment]
👍

**Comment by mulieli** [comment]
> 最近项目组准备在线上的项目中应用MXFlutter，大佬能否透露一下大版本更新的时间。
> 感谢！

@coderLM 
请问你们线上用的怎么样

**Comment by coderLM** [comment]
我不是大佬... 你QQ群里问问soap
