### ISSUE TITLE
为什么限制 withSourceURL 中路径的长度？

### ISSUE THREAD

**Issue by RenderCoder** [TGIF-iMatrix/MXFlutter#30]
具体问题是这一行：
```
jsFilePathPrefix = [jsFilePathPrefix substringFromIndex:jsFilePathPrefix.length - preixLen];
```
文件地址：
https://github.com/mxflutter/mxflutter/blob/0fa769af6c1e5403184c810d31c3cf0588956431/mxflutter/ios/Classes/MXFlutterOCFramework/JSModule.m#L230

如果对 JS 文件路径进行截断，会导致在真机运行时文件路径错误，iOS JavaScriptCore 执行文件内容会失败，这里这样做的考虑是什么？（想了解 230 行存在的理由）

**Comment by mxflutter** [comment]
原路径太长，导致用safari 调试时无法看到是哪个JS文件，如果只用JS文件名，不同目录相同JS文件可能搞混，看有无更好的方法。 真机路径错误问题，我们没有遇到，贴一下错误看看。
