### ISSUE TITLE
Support Typescript

### ISSUE THREAD

**Issue by jctaoo** [TGIF-iMatrix/MXFlutter#31]
- 跟 JS 相比， 同样具有脚本语言特性， 但有更好但类型系统。
- 或许可以利用 .d.ts 文件来帮助 mxflutter 来使用 dart 生态。

**Comment by mxflutter** [comment]
感谢jctaoo建议，目前在评估重构方案，ts在计划中

**Comment by d1y** [comment]
同求 希望出ts版本

**Comment by mxflutter** [comment]
v0.8.0版本已支持
