### ISSUE TITLE
错误 undefined:174: TypeError: Cannot read property

### ISSUE THREAD

**Issue by waitwalker** [TGIF-iMatrix/MXFlutter#32]
按照步骤接入,能正常运行:
MXJSWidgetHomePage页面能push出来;
MXJSWidgetHomePage里面的列表item随便点击哪个都报错:
I/flutter (14965): MXJSFlutter:[Flutter]-callJSWidget:flutterCallOnEventCallback
D/MXJSFlutter:[Native](14965):  -|[com.mojitox.mxflutter.framework.MXJSFlutterApp$3][onMethodCall][138]|  -|MXJSFlutter : jsFlutterAppChannel callJS:flutterCallOnEventCallback| 
D/MXJSEngine(14965): MXJSFlutter:[JS]-MXJSFlutterApp:nativeCall[object Object]
D/MXJSEngine(14965): MXJSFlutter:[JS]-JSWidget invokeCallback ::WidgetInfo: Name: undefined Class: MXJSStatefulWidget WID: 5 buildseq: 1 currentTreeSeq: 1 buildingseq: 1 preTreeSeq: 1 buildWidgetDataSeq: 1 callID: 5/21
E/MXJSExecutor(14965): 
E/MXJSExecutor(14965): undefined:174: TypeError: Cannot read property 'JSPestoPage' of null
E/MXJSExecutor(14965):                                 return new pesto.JSPestoPage;
E/MXJSExecutor(14965):                                                  ^
E/MXJSExecutor(14965): TypeError: Cannot read property 'JSPestoPage' of null
E/MXJSExecutor(14965):     at MaterialPageRoute.builder (<anonymous>:174:50)
E/MXJSExecutor(14965):     at NavigatorState.push (<anonymous>:1212:64)
E/MXJSExecutor(14965):     at Function.push (<anonymous>:1246:20)
E/MXJSExecutor(14965):     at onTap (<anonymous>:172:35)
E/MXJSExecutor(14965):     at MXJSWidgetTree.invokeCallback (<anonymous>:483:12)
E/MXJSExecutor(14965):     at MXJSWidgetHelper.invokeCallback (<anonymous>:856:44)
E/MXJSExecutor(14965):     at MXJSWidgetHelper.onEventCallback (<anonymous>:756:30)
E/MXJSExecutor(14965):     at MyApp.flutterCallOnEventCallback (<anonymous>:421:35)
E/MXJSExecutor(14965):     at MyApp.nativeCall (<anonymous>:405:18)
E/MXJSExecutor(14965): com.eclipsesource.v8.V8ScriptExecutionException
E/MXJSExecutor(14965): 	at com.eclipsesource.v8.V8._executeFunction(Native Method)
E/MXJSExecutor(14965): 	at com.eclipsesource.v8.V8.executeFunction(V8.java:1162)
E/MXJSExecutor(14965): 	at com.eclipsesource.v8.V8Object.executeFunction(V8Object.java:370)
E/MXJSExecutor(14965): 	at com.mojitox.mxflutter.framework.MXJSExecutor$13.excute(MXJSExecutor.java:201)
E/MXJSExecutor(14965): 	at com.mojitox.mxflutter.framework.utils.MXJsScheduledExecutorService$MXJsTask.run(MXJsScheduledExecutorService.java:71)
E/MXJSExecutor(14965): 	at com.mojitox.mxflutter.framework.utils.MXJsScheduledExecutorService.execute(MXJsScheduledExecutorService.java:57)
E/MXJSExecutor(14965): 	at com.mojitox.mxflutter.framework.MXJSExecutor.invokeJSValue(MXJSExecutor.java:195)
E/MXJSExecutor(14965): 	at com.mojitox.mxflutter.framework.MXJSFlutterApp$3$1.excute(MXJSFlutterApp.java:148)
E/MXJSExecutor(14965): 	at com.mojitox.mxflutter.framework.utils.MXJsScheduledExecutorService$MXJsTask.run(MXJsScheduledExecutorService.java:71)
E/MXJSExecutor(14965): 	at com.mojitox.mxflutter.framework.utils.MXJsScheduledExecutorService.execute(MXJsScheduledExecutorService.java:57)
E/MXJSExecutor(14965): 	at com.mojitox.mxflutter.framework.MXJSExecutor.execute(MXJSExecutor.java:49)
E/MXJSExecutor(14965): 	at com.mojitox.mxflutter.framework.MXJSFlutterApp$3.onMethodCall(MXJSFlutterApp.java:144)
E/MXJSExecutor(14965): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MXJSExecutor(14965): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MXJSExecutor(14965): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MXJSExecutor(14965): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MXJSExecutor(14965): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MXJSExecutor(14965): 	at android.os.Looper.loop(Looper.java:190)
E/MXJSExecutor(14965): 	at android.app.ActivityThread.main(ActivityThread.java:7275)
E/MXJSExecutor(14965): 	at java.lang.reflect.Method.invoke(Native Method)
E/MXJSExecutor(14965): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
E/MXJSExecutor(14965): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)

**Comment by wu928320442** [comment]
哪里的问题啊 我也遇到这个问题了

**Comment by waitwalker** [comment]
> 哪里的问题啊 我也遇到这个问题了

把用到的js脚本文件,都要在Flutter里面加载一下
