### ISSUE TITLE
编译时候报错

### ISSUE THREAD

**Issue by Corol** [TGIF-iMatrix/MXFlutter#35]
git clone 后，
下载依赖
然后报错。
报错位置在：
/lib/src/mx_json_proxy_cupertino.dart
line 395 CupertinoFullscreenDialogTransition
报错内容：

mxflutter/lib/src/mx_json_proxy_cupertino.dart:397:7: Error: No named parameter with the name 'primaryRouteAnimation'.

![image](https://user-images.githubusercontent.com/19591550/87305246-bac4d380-c548-11ea-93be-ba823dc3d6c7.png)

**Comment by qq2339300630** [comment]
我也遇到了这么问题，有大佬解决了么

**Comment by prczhb** [comment]
尝试切换下flutter的版本. 我没用过这个东西 不过我猜是flutter版本不匹配的问题

**Comment by mxflutter** [comment]
flutter 版本不对，使用对应版本编译
