### ISSUE TITLE
更新js 文件 产生这个错误

### ISSUE THREAD

**Issue by ryan730** [TGIF-iMatrix/MXFlutter#4]
更新js 文件 产生这个错误

Error 105 received from application: Isolate must be runnable
Unhandled exception:
{code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: true, rootLibUri: file:///Users/ryan/Library/Developer/CoreSimulator/Devices/DF9EE301-B1BE-4863-A915-E9531CB32C2E/data/Containers/Data/Application/588E43D2-D23D-48A3-A0A0-014F42E1F51E/tmp/MXFlutterXdUBxt/MXFlutter/lib/main.dart.incremental.dill, packagesUri: file:///Users/ryan/Library/Developer/CoreSimulator/Devices/DF9EE301-B1BE-4863-A915-E9531CB32C2E/data/Containers/Data/Application/588E43D2-D23D-48A3-A0A0-014F42E1F51E/tmp/MXFlutterXdUBxt/MXFlutter/.packages, isolateId: isolates/323409572}}, details: Isolate must be runnable before this request is made.}}
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

**Comment by TGIF-lucaliu** [comment]
能具体描述下吗？

**Comment by OOMROO** [comment]
修改JS 文件 热更新报 Error 105 received from application: Isolate must be runnable

**Comment by mxflutter** [comment]
可以忽略这个错误，热更新JS需要在Demo 首页上点击 “Reload JSApp”，重新进入
