### ISSUE TITLE
English Documentation

### ISSUE THREAD

**Issue by realprabs** [TGIF-iMatrix/MXFlutter#5]
Got here from https://github.com/flutter/flutter/issues/14330#issuecomment-506595602. You may want to consider providing some English documentation for the rest of us.

**Comment by yoferzhang** [comment]
Thank you for your attention, we will provide English Documents ASAP.

**Comment by yoferzhang** [comment]
> Got here from [flutter/flutter#14330 (comment)](https://github.com/flutter/flutter/issues/14330#issuecomment-506595602). You may want to consider providing some English documentation for the rest of us.

Thank you for your attention, we will provide English Documents ASAP.

**Comment by yoferzhang** [comment]
> Got here from [flutter/flutter#14330 (comment)](https://github.com/flutter/flutter/issues/14330#issuecomment-506595602). You may want to consider providing some English documentation for the rest of us.

English documents have been online, please check here
[readme](https://github.com/TGIF-iMatrix/MXFlutter/blob/master/Documentation/readmeEnglish.md)

[introduce](https://github.com/TGIF-iMatrix/MXFlutter/blob/master/Documentation/introduceEnglish.md)
