### ISSUE TITLE
MXFlutter开发技术交流qq群 621812240

### ISSUE THREAD

**Issue by bobzhou80** [TGIF-iMatrix/MXFlutter#6]
很看好这个动态框架，感兴趣的同学一起交流经验，欢迎大牛和作者加入

**Comment by mxflutter** [comment]
> 很看好这个动态框架，感兴趣的同学一起交流经验，欢迎大牛和作者加入

对MXFlutter有兴趣的小伙伴，可以加官方交流群 QQ群:747535761
