### ISSUE TITLE
提示点击demo选项 提示widgetData=null pop

### ISSUE THREAD

**Issue by bobzhou80** [TGIF-iMatrix/MXFlutter#7]
提示点击demo选项 提示widgetData=null pop ，是什么问题呢？

**Comment by bobzhou80** [comment]
MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke_3|[85]-mxInclude file:js_flutter_framework.js
MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke_3|[85]-mxInclude file:js_flutter_basic_types.js
MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke_3|[85]-mxInclude file:js_flutter_text.js
MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke_3|[85]-mxInclude file:home_page.js
MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke_3|[85]-mxInclude file:js_flutter_ui.js
MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke|[74]-js context.exceptionHandler  SyntaxError: Unexpected token '...'. Expected a property name.
MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke|[74]-js context.exceptionHandler  TypeError: Right side of assignment cannot be destructured
MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke|[74]-js context.exceptionHandler  TypeError: Right side of assignment cannot be destructured
MXJSFlutter:[Native]-|-[MXJSFlutterApp runAppWithPageName:]_block_invoke_2|[127]-MXJSFlutter : runApp error:(null)
Syncing files to device iPhone X...
flutter: MXJSFlutter:[Flutter]-Alignment is Alignment(0.0, 0.5)
flutter: MXJSFlutter:[Flutter]-callJSWidget:MethodCall(flutterCallNavigatorPushWithPageName, {pageName: app_test, themeData: {brightness: Brightness.light, primaryColor: 4294940672, primaryColorBrightness: Brightness.light, primaryColorLight: 4294959282, primaryColorDark: 4294278144, accentColor: 4294940672, accentColorBrightness: Brightness.light, canvasColor: 4294638330, scaffoldBackgroundColor: 4294638330, bottomAppBarColor: 4294967295, cardColor: 4294967295, dividerColor: 520093696, highlightColor: 1723645116, splashColor: 1724434632, selectedRowColor: 4294309365, unselectedWidgetColor: 2315255808, disabledColor: 1627389952, buttonColor: 4292927712, secondaryHeaderColor: 4294964192, textSelectionColor: 4294954112, backgroundColor: 4294954112, dialogBackgroundColor: 4294967295, indicatorColor: 4294940672, hintColor: 2315255808, errorColor: 4292030255, toggleableActiveColor: 4294675456, textTheme: {display4: {inherit: false, color: 2315255808, fontSize: 112.0, fontWeight: FontWeight.w100, fon<…>
flutter: MXJSFlutter:[Flutter]-callJSWidget:MethodCall(flutterCallOnInitState, {widgetID: null, buildSeq: null})
flutter: MXJSFlutter:[Flutter]-MXJSWidget:build: null

ios 运行错误，需要如何运行呢？

**Comment by langbluesky** [comment]
> MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke_3|[85]-mxInclude file:js_flutter_framework.js
> MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke_3|[85]-mxInclude file:js_flutter_basic_types.js
> MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke_3|[85]-mxInclude file:js_flutter_text.js
> MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke_3|[85]-mxInclude file:home_page.js
> MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke_3|[85]-mxInclude file:js_flutter_ui.js
> MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke|[74]-js context.exceptionHandler SyntaxError: Unexpected token '...'. Expected a property name.
> MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke|[74]-js context.exceptionHandler TypeError: Right side of assignment cannot be destructured
> MXJSFlutter:[Native]-|setupBasicJSRuntime_block_invoke|[74]-js context.exceptionHandler TypeError: Right side of assignment cannot be destructured
> MXJSFlutter:[Native]-|-[MXJSFlutterApp runAppWithPageName:]_block_invoke_2|[127]-MXJSFlutter : runApp error:(null)
> Syncing files to device iPhone X...
> flutter: MXJSFlutter:[Flutter]-Alignment is Alignment(0.0, 0.5)
> flutter: MXJSFlutter:[Flutter]-callJSWidget:MethodCall(flutterCallNavigatorPushWithPageName, {pageName: app_test, themeData: {brightness: Brightness.light, primaryColor: 4294940672, primaryColorBrightness: Brightness.light, primaryColorLight: 4294959282, primaryColorDark: 4294278144, accentColor: 4294940672, accentColorBrightness: Brightness.light, canvasColor: 4294638330, scaffoldBackgroundColor: 4294638330, bottomAppBarColor: 4294967295, cardColor: 4294967295, dividerColor: 520093696, highlightColor: 1723645116, splashColor: 1724434632, selectedRowColor: 4294309365, unselectedWidgetColor: 2315255808, disabledColor: 1627389952, buttonColor: 4292927712, secondaryHeaderColor: 4294964192, textSelectionColor: 4294954112, backgroundColor: 4294954112, dialogBackgroundColor: 4294967295, indicatorColor: 4294940672, hintColor: 2315255808, errorColor: 4292030255, toggleableActiveColor: 4294675456, textTheme: {display4: {inherit: false, color: 2315255808, fontSize: 112.0, fontWeight: FontWeight.w100, fon<…>
> flutter: MXJSFlutter:[Flutter]-callJSWidget:MethodCall(flutterCallOnInitState, {widgetID: null, buildSeq: null})
> flutter: MXJSFlutter:[Flutter]-MXJSWidget:build: null
> 
> ios 运行错误，需要如何运行呢？

是自己新写的页面吗？

**Comment by TGIF-lucaliu** [comment]
是自己新写的页面吗？方便贴出代码吗？

**Comment by bobzhou80** [comment]
没有新写页面，直接例子跑起来就是这样，没有改任何代码

**Comment by ktcer** [comment]
同是

**Comment by vanceeasleaf** [comment]
demo一run就报这个bug

**Comment by radiocom** [comment]
你是Android吧, 我看Native层就没有实现 js_flutter.flutter_main_channel.
难道还需要其他的配置?

**Comment by buerkai** [comment]
好像目前还不支持android

**Comment by sungerk** [comment]
android 首次打开不会有这个问题，退出到桌面重新打开必现

**Comment by mxflutter** [comment]
0.0.3版本支持android
