### ISSUE TITLE
这年头只要是个东西都能说成高性能。

### ISSUE THREAD

**Issue by AibiTi** [TGIF-iMatrix/MXFlutter#8]

**Comment by TGIF-iMatrix** [comment]
程序员交流，有问题提问题，有争议提代码^_*

**Comment by AibiTi** [comment]
@TGIF-iMatrix 有本事给出性能测试数据，敢不敢，看你也没有。

**Comment by TGIF-iMatrix** [comment]
> @TGIF-iMatrix 有本事给出性能测试数据，敢不敢，看你也没有。

你这么不友好，我们给的数据你信吗，源码都在这，你可以自己跑。

**Comment by AibiTi** [comment]
果然不敢，你都不会性能测试。

**Comment by TGIF-iMatrix** [comment]
> 果然不敢，你都不会性能测试。

哈哈哈，这找茬的语气好萌萌哒，如果想撩帅哥的话，介绍我们的主程yofer帅哥给你认识 http://yoferzhang.com/post/20180424tokyoanimation/

**Comment by TGIF-iMatrix** [comment]
记得把你账号里的黑历史清一清  https://github.com/zhui-team/zhui/issues/13
